x-logging: &logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"


services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        command: poetry run app
        volumes:
            - "./src/:/app/src"
        depends_on:
            - mongo
        env_file:
            - dotenv/mongo.env
            - dotenv/app.env
        logging: *logging

    mongo:
        image: mongo:7.0.12
        restart: always
        env_file:
            - dotenv/mongo.env
        volumes:
            - appdata:/data/db
        logging: *logging

volumes:
    appdata:
